"""empty message

Revision ID: 4874a6147081
Revises: d050defa5b57
Create Date: 2023-09-13 14:20:24.814265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4874a6147081'
down_revision = 'd050defa5b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
