"""empty message

Revision ID: acd8f83b7cd4
Revises: b29d0954de8d
Create Date: 2023-08-04 17:08:23.832493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acd8f83b7cd4'
down_revision = 'b29d0954de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=250), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('picture')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
